### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by jameswan** [ibaiGorordo/ONNX-YOLOv8-Object-Detection#10]
**image_object_detection.py**

Traceback (most recent call last):
  File "C:\Users\James\Desktop\articles\ONNX-YOLOv8-Object-Detection\image_object_detection.py", line 1, in <module>
    from yolov8 import YOLOv8
  File "C:\Users\James\Desktop\articles\ONNX-YOLOv8-Object-Detection\yolov8\__init__.py", line 1, in <module>
    from .YOLOv8 import YOLOv8
  File "C:\Users\James\Desktop\articles\ONNX-YOLOv8-Object-Detection\yolov8\YOLOv8.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**conda run --name yolo_classify python -c "import sys; print(sys.version); import cv2; print(cv2.__version__)"**
3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)]
4.7.0

**Comment by ibaiGorordo** [comment]
That is probably an issue with your Conda environment or how you run the program
